### ISSUE TITLE
Errors with Internet Explorer 11 and below.

### ISSUE THREAD

**Issue by benbristow** [ampervue/ngJWPlayer#4]
Hey,

This doesn't seem to be a problem with Microsoft Edge, but on Internet Explorer 11 and below I'm getting this error:

TypeError: Unable to get property 'call' of undefined or null reference
   at t (https://content.jwplatform.com/libraries/WRqClAMd.js:1:314)
   at Anonymous function (https://content.jwplatform.com/libraries/WRqClAMd.js:5:15710)
   at t.e (https://content.jwplatform.com/libraries/WRqClAMd.js:1:654)
   at u (https://content.jwplatform.com/libraries/WRqClAMd.js:5:15686)
   at c (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25285)
   at Anonymous function (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25229)
   at w.forEach (https://content.jwplatform.com/libraries/WRqClAMd.js:1:1669)
   at l (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25137)
   at start (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25680)
   at v.prototype.setup (https://content.jwplatform.com/libraries/WRqClAMd.js:5:5736) <jwplayer class="ng-isolate-scope" ng-src="{{videoUrl}}" player-id="v3player" player-options="playerOptions">

And also
ReferenceError: 'Promise' is undefined
   at e.load (https://content.jwplatform.com/libraries/WRqClAMd.js:2:11540)
   at p (https://content.jwplatform.com/libraries/WRqClAMd.js:7:16731)
   at c (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25285)
   at Anonymous function (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25229)
   at w.forEach (https://content.jwplatform.com/libraries/WRqClAMd.js:1:1669)
   at l (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25137)
   at d (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25501)
   at n (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25277)
   at v (https://content.jwplatform.com/libraries/WRqClAMd.js:5:16312)
   at c (https://content.jwplatform.com/libraries/WRqClAMd.js:4:25285)

I don't know why this would be doing this, but I'm going to assume it's something to do with this directive rather than JWPlayer itself.

Hopefully you can get back to me ASAP.
- Ben

**Comment by dkarchmer** [comment]
No access to IE11. Feel free to debug and do a pull request.

**Comment by benbristow** [comment]
It was my fault. I fixed it.

The problem was I added the shaka library after following some guide god knows where. I think there was a conflict somewhere. All's sorted now though.
